const types = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  DELETE_MOVIE: "DELETE_MOVIE",
  ADD_MOVIE: "ADD_MOVIE",
  UPLOAD_MOVIES_START: "UPLOAD_MOVIES_START",
  UPLOAD_MOVIES_SUCCESS: "UPLOAD_MOVIES_SUCCESS",
  UPLOAD_MOVIES_FAILURE: "UPLOAD_MOVIES_FAILURE",
  DISMISS_SUCCESS_ADD: "DISMISS_SUCCESS_ADD",
  DISMISS_SUCCESS_DELETE: "DISMISS_SUCCESS_DELETE"
};

export default types;
