const types = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  DELETE_MOVIE: "DELETE_MOVIE",
  ADD_MOVIE: "ADD_MOVIE"
};

export default types;
